apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ms-orders-pdb
  namespace: {{ include "sa-platform.namespace" . }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
    {{- include "ms-orders.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ms-orders
