apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: sa-platform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  TZ: {{ .Values.timezone | quote }}
  STUDENT_CARNE: {{ .Values.studentCarne | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_HOST: {{ .Values.postgresql.host | quote }}
  DB_PORT: {{ .Values.postgresql.port | quote }}
  DB_NAME: {{ .Values.postgresql.database | quote }}
  DB_USER: {{ .Values.postgresql.username | quote }}
  {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  BROKER_HOST: {{ .Values.rabbitmq.host | quote }}
  BROKER_PORT: {{ .Values.rabbitmq.port | quote }}
  BROKER_USER: {{ .Values.rabbitmq.username | quote }}
  BROKER_SUMMARY_QUEUE: {{ .Values.rabbitmq.summaryQueueName | quote }}
  {{- end }}
