apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ms-users-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ms-users.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ms-users
